### YamlMime:ModuleUnit
uid: learn-bizapps.powerapps-manage.3-powerapps-environments
title: Verstehen von Umgebungen in PowerApps
metadata:
  title: Verstehen von Umgebungen in PowerApps
  description: Erfahren Sie, wie Sie mit Umgebungen in PowerApps arbeiten.
  ms.openlocfilehash: 9441ee0c6ec26e729736d57d32cc15eaa317500e
  ms.sourcegitcommit: 609626c2526eb275d1789eb2a081ff543d89e967
  ms.translationtype: HT
  ms.contentlocale: de-DE
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43192836"
durationInMinutes: 12
content: '[!include[](includes/3-powerapps-environments.md)]'
